export const prefix = 'ICECREAM_SHOPS';
export const FETCH_ICECREAM_SHOPS_START = `${prefix}/FETCH_ICECREAM_SHOPS_START`;
export const FETCH_ICECREAM_SHOPS_SUCCESS = `${prefix}/FETCH_ICECREAM_SHOPS_SUCCESS`;
export const FETCH_ICECREAM_SHOPS_FAIL = `${prefix}/FETCH_ICECREAM_SHOPS_FAIL`;
export const SET_ICECREAM_SHOPS_FILTER = `${prefix}/SET_ICECREAM_SHOPS_FILTER`;