export const prefix = 'VIEW_SHOP';
export const FETCH_ICECREAM_SHOP_START = `${prefix}/FETCH_ICECREAM_SHOP_START`;
export const FETCH_ICECREAM_SHOP_SUCCESS = `${prefix}/FETCH_ICECREAM_SHOP_SUCCESS`;
export const FETCH_ICECREAM_SHOP_FAIL = `${prefix}/FETCH_ICECREAM_SHOP_FAIL`;